// FabLab QR payload format
// =========================
//
// Every ID card generated by the system encodes the person's role
// alongside their national ID:
//
//   FL:{ROLE}:{nationalId}
//
// Examples:
//   FL:STAFF:1234567890      — FabLab staff
//   FL:VOL:1234567890        — Volunteer
//   FL:WORKER:1234567890     — Worker
//   FL:MAWHBA:S00042         — Mawhba student (uses studentId, not nationalId)
//   FL:SUMMER:1234567890     — Summer student
//   FL:INTERN:1234567890     — University intern
//   FL:TRAINER:1234567890    — Trainer assistant
//   FL:WORKSHOP:W-2026-001   — Workshop student
//
// Rationale: the same person can be BOTH staff and a volunteer.
// Without the role in the QR, a scanner on the volunteer attendance
// page can't tell which role the operator meant to check in. With the
// role in the payload, each scan endpoint validates the prefix and
// either processes the scan or returns a clear "wrong scanner" error.
//
// Backward compat: any code that DOESN'T start with FL: is treated as
// a raw ID for the endpoint's own role — so previously-printed cards
// still work everywhere they already worked.

const KNOWN_ROLES = new Set([
  'STAFF', 'VOL', 'WORKER', 'MAWHBA', 'SUMMER', 'INTERN', 'TRAINER', 'WORKSHOP'
]);

const ROLE_LABELS_AR = {
  STAFF:    'موظف فاب لاب',
  VOL:      'متطوع',
  WORKER:   'عامل',
  MAWHBA:   'طالب موهبة',
  SUMMER:   'طالب صيف فاب لاب',
  INTERN:   'متدرب جامعي',
  TRAINER:  'مدرب معاون',
  WORKSHOP: 'طالب ورشة'
};

// Build the QR payload string for a card.
const buildQrPayload = (role, id) => {
  const r = String(role || '').toUpperCase();
  if (!KNOWN_ROLES.has(r)) throw new Error(`Unknown QR role: ${role}`);
  const clean = String(id || '').trim();
  if (!clean) throw new Error('QR id is empty');
  return `FL:${r}:${clean}`;
};

// Parse a scanned code. Returns:
//   { role, id, raw, prefixed: true }   for FL:ROLE:id format
//   { role: null, id: raw, raw, prefixed: false }  for legacy raw payloads
const parseQrPayload = (input) => {
  const raw = String(input || '').trim();
  const m = /^FL:([A-Z]+):(.+)$/.exec(raw);
  if (m && KNOWN_ROLES.has(m[1])) {
    return { role: m[1], id: m[2].trim(), raw, prefixed: true };
  }
  return { role: null, id: raw, raw, prefixed: false };
};

// Middleware-friendly guard used inside each role's scanAttendance
// endpoint. Returns { ok: true, id } when the scan is valid for the
// expected role, or { ok: false, status, response } otherwise.
const requireRole = (input, expectedRole) => {
  const parsed = parseQrPayload(input);
  const expected = String(expectedRole || '').toUpperCase();
  if (!KNOWN_ROLES.has(expected)) return { ok: true, id: parsed.id, parsed };
  if (parsed.role && parsed.role !== expected) {
    return {
      ok: false,
      status: 409,
      response: {
        error: 'wrong_role',
        message: `This QR belongs to a different role (${parsed.role}) — please use the correct scanner.`,
        messageAr: `هذا الرمز خاص بـ"${ROLE_LABELS_AR[parsed.role] || parsed.role}" — يرجى استخدام محطة المسح المناسبة.`,
        scannedRole: parsed.role,
        expectedRole: expected,
        code: parsed.raw
      }
    };
  }
  return { ok: true, id: parsed.id, parsed };
};

module.exports = {
  buildQrPayload,
  parseQrPayload,
  requireRole,
  KNOWN_ROLES,
  ROLE_LABELS_AR
};
